import '@/styles/globals.css'
import { Outfit } from 'next/font/google'
import ScrollSmootherLayout from '@/components/layout/scroll-smoother-layout'

import type { Metadata } from 'next'

const outfitFont = Outfit({
  variable: '--font-outfit',
  fallback: ['sans-serif'],
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: {
    template: '%s - Edotel: How To',
    default: 'Edotel: How To',
  },
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfitFont.variable} antialiased font-sans`}
        suppressHydrationWarning
      >
        <ScrollSmootherLayout>{children}</ScrollSmootherLayout>
      </body>
    </html>
  )
}
